/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criptosubstituicao;

import java.awt.Container;
import java.awt.Cursor;
import java.io.File;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author willi
 */
public class FramePrincipal extends javax.swing.JFrame
{
    private char[] cifraSubstituicao;
    public String[] freqLetras = null;
    private JLabel[] letrasLabel;
    private String textoOriginal;
    private TableModelListener tabelaCifraListener;
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        
        // centraliza janela na tela
        this.setLocationRelativeTo(null);
        
        // centralizar conteúdo das colunas das tabelas das cifras de substituição
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        cifraTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        cifraTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);

        // Listener para capturar eventos de alteração de dados nas tabelas
        tabelaCifraListener = (TableModelEvent evt) -> 
        {
            cifraCriptografiaMudou(evt);
        };

        // habilita eventos de alteração de dados nas tabelas
        habilitaAlteracoesTabelaCifra();
        
        // cria e limpa cifra de substituicao
        cifraSubstituicao = new char[26];
        for(int i = 0; i < 26; ++i)
            cifraSubstituicao[i] = ' ';
        
        // inicia vetor de rótulos com as letras
        letrasLabel = new JLabel[26];
        for(int i = 0; i < 26; ++i)
        {
            switch(i)
            {
                case 0: letrasLabel[0] = aJLabel; break;
                case 1: letrasLabel[1] = bJLabel; break;
                case 2: letrasLabel[2] = cJLabel; break;
                case 3: letrasLabel[3] = dJLabel; break;
                case 4: letrasLabel[4] = eJLabel; break;
                case 5: letrasLabel[5] = fJLabel; break;
                case 6: letrasLabel[6] = gJLabel; break;
                case 7: letrasLabel[7] = hJLabel; break;
                case 8: letrasLabel[8] = iJLabel; break;
                case 9: letrasLabel[9] = jJLabel; break;
                case 10: letrasLabel[10] = kJLabel; break;
                case 11: letrasLabel[11] = lJLabel; break;
                case 12: letrasLabel[12] = mJLabel; break;
                case 13: letrasLabel[13] = nJLabel; break;
                case 14: letrasLabel[14] = oJLabel; break;
                case 15: letrasLabel[15] = pJLabel; break;
                case 16: letrasLabel[16] = qJLabel; break;
                case 17: letrasLabel[17] = rJLabel; break;
                case 18: letrasLabel[18] = sJLabel; break;
                case 19: letrasLabel[19] = tJLabel; break;
                case 20: letrasLabel[20] = uJLabel; break;
                case 21: letrasLabel[21] = vJLabel; break;
                case 22: letrasLabel[22] = wJLabel; break;
                case 23: letrasLabel[23] = xJLabel; break;
                case 24: letrasLabel[24] = yJLabel; break;
                case 25: letrasLabel[25] = zJLabel; break;
            }
            
            letrasLabel[i].setForeground(java.awt.Color.gray);
        }
    }
    
    // habilita eventos de alteração de dados nas tabelas
    private void habilitaAlteracoesTabelaCifra()
    {
        cifraTable.getModel().addTableModelListener(tabelaCifraListener);
    }
    
    // desabilita eventos de alteração de dados nas tabelas
    private void desabilitaAlteracoesTabelaCifra()
    {
        cifraTable.getModel().removeTableModelListener(tabelaCifraListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        sairJButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        arqEntradaTextField = new javax.swing.JTextField();
        buscaArqEntradaJButton = new javax.swing.JButton();
        lerArqEntradaJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arqSaidaTextField = new javax.swing.JTextField();
        buscaArqSaidaJButton = new javax.swing.JButton();
        gravarArqSaidaJButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        kJLabel = new javax.swing.JLabel();
        tJLabel = new javax.swing.JLabel();
        rJLabel = new javax.swing.JLabel();
        fJLabel = new javax.swing.JLabel();
        lJLabel = new javax.swing.JLabel();
        cJLabel = new javax.swing.JLabel();
        vJLabel = new javax.swing.JLabel();
        zJLabel = new javax.swing.JLabel();
        yJLabel = new javax.swing.JLabel();
        hJLabel = new javax.swing.JLabel();
        bJLabel = new javax.swing.JLabel();
        qJLabel = new javax.swing.JLabel();
        pJLabel = new javax.swing.JLabel();
        sJLabel = new javax.swing.JLabel();
        mJLabel = new javax.swing.JLabel();
        gJLabel = new javax.swing.JLabel();
        oJLabel = new javax.swing.JLabel();
        dJLabel = new javax.swing.JLabel();
        uJLabel = new javax.swing.JLabel();
        eJLabel = new javax.swing.JLabel();
        wJLabel = new javax.swing.JLabel();
        nJLabel = new javax.swing.JLabel();
        xJLabel = new javax.swing.JLabel();
        jJLabel = new javax.swing.JLabel();
        iJLabel = new javax.swing.JLabel();
        aJLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cifraTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        arqTextArea = new javax.swing.JTextArea();
        verFreqLetrasJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criptografia por Substituição Monoalfabética");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        sairJButton.setText("Sair");
        sairJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sairJButtonActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos"));

        arqEntradaTextField.setEditable(false);
        arqEntradaTextField.setToolTipText("Arquivo criptografado a ser processado");

        buscaArqEntradaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criptosubstituicao/resources/search.png"))); // NOI18N
        buscaArqEntradaJButton.setToolTipText("Selecionar arquivo criptografado");
        buscaArqEntradaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaArqEntradaJButtonActionPerformed(evt);
            }
        });

        lerArqEntradaJButton.setText("Ler");
        lerArqEntradaJButton.setEnabled(false);
        lerArqEntradaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lerArqEntradaJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Entrada:");

        jLabel3.setText("Saída:");

        arqSaidaTextField.setEditable(false);
        arqSaidaTextField.setToolTipText("Arquivo criptografado a ser processado");

        buscaArqSaidaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/criptosubstituicao/resources/search.png"))); // NOI18N
        buscaArqSaidaJButton.setToolTipText("Selecionar arquivo criptografado");
        buscaArqSaidaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaArqSaidaJButtonActionPerformed(evt);
            }
        });

        gravarArqSaidaJButton.setText("Gravar");
        gravarArqSaidaJButton.setEnabled(false);
        gravarArqSaidaJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gravarArqSaidaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(arqSaidaTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaArqSaidaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(arqEntradaTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscaArqEntradaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lerArqEntradaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravarArqSaidaJButton))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(arqEntradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lerArqEntradaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaArqEntradaJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(arqSaidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gravarArqSaidaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaArqSaidaJButton))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        kJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kJLabel.setForeground(new java.awt.Color(153, 153, 153));
        kJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kJLabel.setText("K");
        kJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        kJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        kJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        tJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tJLabel.setForeground(new java.awt.Color(153, 153, 153));
        tJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJLabel.setText("T");
        tJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        tJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        tJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        rJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rJLabel.setForeground(new java.awt.Color(153, 153, 153));
        rJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rJLabel.setText("R");
        rJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        rJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        rJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        fJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fJLabel.setForeground(new java.awt.Color(153, 153, 153));
        fJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fJLabel.setText("F");
        fJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        fJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        fJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        lJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lJLabel.setForeground(new java.awt.Color(153, 153, 153));
        lJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJLabel.setText("L");
        lJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        lJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        lJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        cJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cJLabel.setForeground(new java.awt.Color(153, 153, 153));
        cJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cJLabel.setText("C");
        cJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        cJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        cJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        vJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vJLabel.setForeground(new java.awt.Color(153, 153, 153));
        vJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vJLabel.setText("V");
        vJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        vJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        vJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        zJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zJLabel.setForeground(new java.awt.Color(153, 153, 153));
        zJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zJLabel.setText("Z");
        zJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        zJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        zJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        yJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yJLabel.setForeground(new java.awt.Color(153, 153, 153));
        yJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yJLabel.setText("Y");
        yJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        yJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        yJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        hJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hJLabel.setForeground(new java.awt.Color(153, 153, 153));
        hJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hJLabel.setText("H");
        hJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        hJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        hJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        bJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bJLabel.setForeground(new java.awt.Color(153, 153, 153));
        bJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bJLabel.setText("B");
        bJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        bJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        bJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        qJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qJLabel.setForeground(new java.awt.Color(153, 153, 153));
        qJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qJLabel.setText("Q");
        qJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        qJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        qJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        pJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pJLabel.setForeground(new java.awt.Color(153, 153, 153));
        pJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pJLabel.setText("P");
        pJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        pJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        pJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        sJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sJLabel.setForeground(new java.awt.Color(153, 153, 153));
        sJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sJLabel.setText("S");
        sJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        sJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        sJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        mJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mJLabel.setForeground(new java.awt.Color(153, 153, 153));
        mJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mJLabel.setText("M");
        mJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        mJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        mJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        gJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gJLabel.setForeground(new java.awt.Color(153, 153, 153));
        gJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gJLabel.setText("G");
        gJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        gJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        gJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        oJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oJLabel.setForeground(new java.awt.Color(153, 153, 153));
        oJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oJLabel.setText("O");
        oJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        oJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        oJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        dJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dJLabel.setForeground(new java.awt.Color(153, 153, 153));
        dJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dJLabel.setText("D");
        dJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        dJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        dJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        uJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uJLabel.setForeground(new java.awt.Color(153, 153, 153));
        uJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uJLabel.setText("U");
        uJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        uJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        uJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        eJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eJLabel.setForeground(new java.awt.Color(153, 153, 153));
        eJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eJLabel.setText("E");
        eJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        eJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        eJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        wJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wJLabel.setForeground(new java.awt.Color(153, 153, 153));
        wJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wJLabel.setText("W");
        wJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        wJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        wJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        nJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nJLabel.setForeground(new java.awt.Color(153, 153, 153));
        nJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nJLabel.setText("N");
        nJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        nJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        nJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        xJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xJLabel.setForeground(new java.awt.Color(153, 153, 153));
        xJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xJLabel.setText("X");
        xJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        xJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        xJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        jJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jJLabel.setForeground(new java.awt.Color(153, 153, 153));
        jJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJLabel.setText("J");
        jJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        jJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        jJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        iJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iJLabel.setForeground(new java.awt.Color(153, 153, 153));
        iJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iJLabel.setText("I");
        iJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        iJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        iJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        aJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aJLabel.setForeground(new java.awt.Color(153, 153, 153));
        aJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aJLabel.setText("A");
        aJLabel.setMaximumSize(new java.awt.Dimension(15, 17));
        aJLabel.setMinimumSize(new java.awt.Dimension(15, 17));
        aJLabel.setPreferredSize(new java.awt.Dimension(15, 17));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(aJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(aJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cifra Substituição"));

        cifraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"a", null},
                {"b", null},
                {"c", null},
                {"d", null},
                {"e", null},
                {"f", null},
                {"g", null},
                {"h", null},
                {"i", null},
                {"j", null},
                {"k", null},
                {"l", null},
                {"m", null},
                {"n", null},
                {"o", null},
                {"p", null},
                {"q", null},
                {"r", null},
                {"s", null},
                {"t", null},
                {"u", null},
                {"v", null},
                {"w", null},
                {"x", null},
                {"y", null},
                {"z", null}
            },
            new String []
            {
                "Crip", "Decr"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        cifraTable.setToolTipText("");
        cifraTable.setCellSelectionEnabled(true);
        cifraTable.setEnabled(false);
        jScrollPane4.setViewportView(cifraTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Conteúdo do Arquivo"));

        arqTextArea.setEditable(false);
        arqTextArea.setColumns(20);
        arqTextArea.setLineWrap(true);
        arqTextArea.setRows(5);
        jScrollPane3.setViewportView(arqTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(25, 25, 25))
        );

        verFreqLetrasJButton.setText("<html><center>Ver Freq<br/>Letras</center></html>");
        verFreqLetrasJButton.setEnabled(false);
        verFreqLetrasJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                verFreqLetrasJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sairJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verFreqLetrasJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(sairJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verFreqLetrasJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Encerra programa. Os ajustes finais de encerramento deverão
    // ser processados no evento formWindowClosing(), que será
    // chamado quando o frame principal for encerrar
    private void sairJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairJButtonActionPerformed
        Container frame = sairJButton.getParent();
        do
        {
            frame = frame.getParent(); 
        }while (!(frame instanceof JFrame));  
        ((JFrame)frame).dispose();
    }//GEN-LAST:event_sairJButtonActionPerformed

    // Frame principal será fechado (encerramento do programa).
    // Fazer os ajustes finais de encerramento
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // FALTA IMPLEMENTAR
    }//GEN-LAST:event_formWindowClosing

    private String escolheArquivo(String localInicial, boolean salvar)
    {
        // objeto GUI para escolher arquivo
        JFileChooser escolheArq = new JFileChooser();
        
        // extensão padrão do arquivo criptografado: .TXT
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
                    "Arquivos texto (*.txt)", "txt");
        escolheArq.setFileFilter(filtro);
        escolheArq.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        // pasta inicial
        if((localInicial == null ) || localInicial.isEmpty())
        {
            // diretório de trabalho corrente
            Path path = FileSystems.getDefault().getPath(".");
            escolheArq.setCurrentDirectory(path.toFile());
        }
        else
        {
            // local do último arquivo selecionado
            File arq = new File(localInicial);
            escolheArq.setCurrentDirectory(arq);
        }
        
        // mostra caixa de diálogo para usuário escolher arquivo
        int ret;
        if(salvar)
        {
            escolheArq.setDialogTitle("Escolhe arquivo de saída");
            ret = escolheArq.showSaveDialog(this);
        }
        else
        {
            // somente diretórios poderão ser escolhidos
            escolheArq.setDialogTitle("Escolhe arquivo de entrada");
            ret = escolheArq.showOpenDialog(this);
        }
        
        
        // verifica se usuário escolheu arquivo
        if(ret == JFileChooser.APPROVE_OPTION)
            // nome do arquivo selecionado pelo usuário
            return escolheArq.getSelectedFile().getPath();
        else
            return null;    // indica que usuário não escolheu arquivo
    }
    
    private void buscaArqEntradaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaArqEntradaJButtonActionPerformed
    {//GEN-HEADEREND:event_buscaArqEntradaJButtonActionPerformed
        String arq = escolheArquivo(arqEntradaTextField.getText(), false);
        if(arq == null)
            lerArqEntradaJButton.setEnabled(arqEntradaTextField.getText().isEmpty() == false);
        else
        {
            arqEntradaTextField.setText(arq);
            lerArqEntradaJButton.setEnabled(true);
        }
    }//GEN-LAST:event_buscaArqEntradaJButtonActionPerformed

    // leitura do arquivo de entrada
    private void lerArqEntradaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lerArqEntradaJButtonActionPerformed
    {//GEN-HEADEREND:event_lerArqEntradaJButtonActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ArquivoTexto arq = new ArquivoTexto(arqEntradaTextField.getText());
        
        // leitura do arquivo e mostra mensagem
        String conteudo = arq.lerArquivo();
        if(conteudo == null) 
        {
            JOptionPane.showMessageDialog(null, arq.getErro(),
                    "Leitura do arquivo",
                    JOptionPane.ERROR_MESSAGE);
            
            textoOriginal = "";
            freqLetras = null;
            arqTextArea.setText("");
            cifraTable.setEnabled(false);
            verFreqLetrasJButton.setEnabled(false);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        
        textoOriginal = conteudo;
        arqTextArea.setText(conteudo);
        cifraTable.setEnabled(true);
        verFreqLetrasJButton.setEnabled(true);
        freqLetras = arq.getFrequenciaLetras();
        arqTextArea.setCaretPosition(0);
        
        // limpa cifra de substituição
        desabilitaAlteracoesTabelaCifra();
        for(int i = 0; i < 26; ++i)
        {
            cifraSubstituicao[i] = ' ';
            letrasLabel[i].setForeground(java.awt.Color.gray);
            cifraTable.setValueAt("", i, 1);
        }
        habilitaAlteracoesTabelaCifra();

        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lerArqEntradaJButtonActionPerformed

    private void buscaArqSaidaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaArqSaidaJButtonActionPerformed
    {//GEN-HEADEREND:event_buscaArqSaidaJButtonActionPerformed
        String arq = escolheArquivo(arqSaidaTextField.getText(), true);
        if(arq == null)
            gravarArqSaidaJButton.setEnabled(arqSaidaTextField.getText().isEmpty() == false);
        else
        {
            arqSaidaTextField.setText(arq);
            gravarArqSaidaJButton.setEnabled(true);
        }
    }//GEN-LAST:event_buscaArqSaidaJButtonActionPerformed

    private void gravarArqSaidaJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gravarArqSaidaJButtonActionPerformed
    {//GEN-HEADEREND:event_gravarArqSaidaJButtonActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ArquivoTexto arq = new ArquivoTexto(arqSaidaTextField.getText());
        
        // grava arquivo e mostra mensagem
        if(arq.gravarArquivo(arqTextArea.getText()))
        {
            JOptionPane.showMessageDialog(null,
                    "Arquivo gravado com sucesso",
                    "Gravação do arquivo",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, arq.getErro(),
                    "Gravação do arquivo",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_gravarArqSaidaJButtonActionPerformed

    private void verFreqLetrasJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_verFreqLetrasJButtonActionPerformed
    {//GEN-HEADEREND:event_verFreqLetrasJButtonActionPerformed
        FreqLetrasDlg dlg = new FreqLetrasDlg(this, true);
        dlg.setFreqLetras(freqLetras);
        dlg.setVisible(true);
    }//GEN-LAST:event_verFreqLetrasJButtonActionPerformed

    // processamento de evento de alteração de dados na
    // tabela de cifra de criptografia
    private void cifraCriptografiaMudou(TableModelEvent evt)
    {
        if(evt.getColumn() != 1)
            return;
        
        String s;
        for(int i = evt.getFirstRow(); i <= evt.getLastRow(); ++i)
        {
            s = (String)cifraTable.getValueAt(i, 1);
            if((s == null) || s.isEmpty())
                cifraSubstituicao[i] = ' ';
            else
                cifraSubstituicao[i] = s.toUpperCase().charAt(0);
        }
                
        // verifica a cifra
        validaCifra();

        // substitui caracteres no conteúdo original
        s = "";
        char c;
        for (int i = 0; i < textoOriginal.length(); i++)
        {
           c = textoOriginal.charAt(i);
           if (Character.isLetter(c) && (cifraSubstituicao[(int)(c - 'a')] != ' '))
               c = cifraSubstituicao[(int)(c - 'a')];
           
           s += c;
        }                
        
        arqTextArea.setText(s);    // mostra novo conteúdo
        arqTextArea.setCaretPosition(0);
    }
    
    // valida cifra de substituição
    private void validaCifra()
    {
        int[] contagem = new int[26];
        for(int i = 0; i < 26; ++i)
            contagem[i] = 0;
        
        for(int i = 0; i < 26; ++i)
        {
            if(cifraSubstituicao[i] != ' ')
                ++contagem[(int)(cifraSubstituicao[i] - 'A')];
        }
        
        // mostra caracteres já escolhidos na cifra de substituição
        for(int i = 0; i < 26; ++i)
        {
            if(contagem[i] == 0)
                letrasLabel[i].setForeground(java.awt.Color.gray);
            else
                if(contagem[i] == 1)
                    letrasLabel[i].setForeground(java.awt.Color.black);
                else
                        letrasLabel[i].setForeground(java.awt.Color.red);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aJLabel;
    private javax.swing.JTextField arqEntradaTextField;
    private javax.swing.JTextField arqSaidaTextField;
    private javax.swing.JTextArea arqTextArea;
    private javax.swing.JLabel bJLabel;
    private javax.swing.JButton buscaArqEntradaJButton;
    private javax.swing.JButton buscaArqSaidaJButton;
    private javax.swing.JLabel cJLabel;
    private javax.swing.JTable cifraTable;
    private javax.swing.JLabel dJLabel;
    private javax.swing.JLabel eJLabel;
    private javax.swing.JLabel fJLabel;
    private javax.swing.JLabel gJLabel;
    private javax.swing.JButton gravarArqSaidaJButton;
    private javax.swing.JLabel hJLabel;
    private javax.swing.JLabel iJLabel;
    private javax.swing.JLabel jJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel kJLabel;
    private javax.swing.JLabel lJLabel;
    private javax.swing.JButton lerArqEntradaJButton;
    private javax.swing.JLabel mJLabel;
    private javax.swing.JLabel nJLabel;
    private javax.swing.JLabel oJLabel;
    private javax.swing.JLabel pJLabel;
    private javax.swing.JLabel qJLabel;
    private javax.swing.JLabel rJLabel;
    private javax.swing.JLabel sJLabel;
    private javax.swing.JButton sairJButton;
    private javax.swing.JLabel tJLabel;
    private javax.swing.JLabel uJLabel;
    private javax.swing.JLabel vJLabel;
    private javax.swing.JButton verFreqLetrasJButton;
    private javax.swing.JLabel wJLabel;
    private javax.swing.JLabel xJLabel;
    private javax.swing.JLabel yJLabel;
    private javax.swing.JLabel zJLabel;
    // End of variables declaration//GEN-END:variables
}
